# Generated by Django 3.2.3 on 2021-05-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotelefono',
            options={'verbose_name': 'Tipo Telefono', 'verbose_name_plural': 'Tipos de Telefono'},
        ),
        migrations.AlterModelTable(
            name='tipotelefono',
            table='Tipo_telefono',
        ),
    ]
