# Generated by Django 3.2.3 on 2021-05-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha expiracion'),
        ),
    ]
