# Generated by Django 3.2.3 on 2021-05-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_fecha_expiracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='existencias',
            new_name='existencia',
        ),
    ]
