# Generated by Django 3.2.3 on 2021-05-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_rename_existencias_producto_existencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='existencia',
            new_name='exitencia',
        ),
    ]
