# Generated by Django 3.2.3 on 2021-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_rename_existencia_producto_exitencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='exitencia',
            field=models.IntegerField(verbose_name='exitecia'),
        ),
    ]
