# Generated by Django 3.2.3 on 2021-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_exitencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='exitencia',
        ),
        migrations.AddField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(default=1, verbose_name='existencia'),
            preserve_default=False,
        ),
    ]
