# Generated by Django 3.2.3 on 2021-05-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210520_2338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
