# Generated by Django 3.2.3 on 2021-05-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0002_auto_20210520_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='genero')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('nit', models.CharField(max_length=10, unique=True, verbose_name='NIT')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='solo incluir numeros', verbose_name='numero de telefono')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Dueño')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Telcliente', to='comun.tipotelefono', verbose_name='Tipo telefono')),
            ],
            options={
                'verbose_name': 'Telefono de cliente',
                'verbose_name_plural': 'Telefonos de Cliente',
            },
        ),
    ]
