# Generated by Django 3.2.3 on 2021-05-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_auto_20210520_2252'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefono',
            options={'verbose_name': 'Telefono de cliente', 'verbose_name_plural': 'Telefonos de Clientes'},
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='telefono',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TelCliente', to='comun.tipotelefono', verbose_name='Tipo telefono'),
        ),
    ]
