# Generated by Django 3.2.3 on 2021-05-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('correo', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
