# Generated by Django 3.2.3 on 2021-05-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dpi',
            field=models.CharField(default='987', max_length=14, verbose_name='DPI'),
            preserve_default=False,
        ),
    ]
