# Generated by Django 3.2.3 on 2021-05-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
        ('empleado', '0005_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='Tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comun.tipotelefono', verbose_name='Tipo telefono'),
            preserve_default=False,
        ),
    ]
