# Generated by Django 3.2.3 on 2021-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_auto_20210520_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='genero'),
        ),
    ]
